name: 'io.naq.github.setup-chromedriver'
description: 'Setup chromedriver'
author: 'johnknaack'
inputs:
  node-version:
    description: 'Node Version'
    required: false
    default: '18.x'
  os:
    description: 'Runner OS'
    required: false
    default: 'ubuntu-latest'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - run: ${{ github.action_path }}/bin/setup-chrome.sh ${{ inputs.os }}
      shell: bash
    - run: ${{ github.action_path }}/bin/setup-lsof.sh ${{ inputs.os }}
      shell: bash
#   - run: ${{ github.action_path }}/bin/setup-chromedriver.sh ${{ inputs.os }}
#     shell: bash
    - run: ${{ github.action_path }}/bin/setup-env.sh ${{ inputs.os }}
      shell: bash
runs.post:
  using: 'composite'
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: output
        path: ./output/*.*
