name: 'build-test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

        #jobs:
        # build:
        # runs-on: ubuntu-20.04 #${{ matrix.os }

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      My_Var: "V0hBVCBUSEUgRlVDSw=="

    steps:
    - name: Decode My_Var
      run: |
        echo "$My_Var should be orig"
        echo "My_Var=""$(echo $My_Var | base64 --decode)""" >> $GITHUB_ENV

    - name: Print My_Var
      run: |
        echo "$My_Var should be new"

        #sudo apt-get update
        #sudo apt-get upgrade -y
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #echo "#####################################################################################################################"
        #sudo apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev
        #git clone https://github.com/rbenv/rbenv.git ~/.rbenv        
        #git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        #git clone https://github.com/rkh/rbenv-whatis.git ~/.rbenv/plugins/rbenv-whatis
        #git clone https://github.com/rkh/rbenv-use.git ~/.rbenv/plugins/rbenv-use
        
        #sudo apt-get install -y libcurl4-openssl-dev
        #cd ~/.rbenv && src/configure && make -C src
        
        #sudo apt-get install build-essential
        
        #echo 'export PATH=$HOME/.rbenv/bin:$PATH' >> ~/.bash_profile
        
        #echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
        #echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
        #source ~/.bash_profile
        

        #rbenv -v
        #rbenv install $VERSION
        #rbenv global $VERSION

    # steps:
    # - uses: actions/checkout@v3
    # - uses: ./
    #
    # - name: Run tests
    #   run: |
    #     npm test
    #
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: output
    #     path: ./output/*.*
    # 
